### ISSUE TITLE
Why does gvar use SVD instead of diagonalization?

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#11]
In general gvar uses SVD instead of diagonalization, for example in gvar.raniter. But for a symmetric matrix it is equivalent to diagonalization, apart from the fact that singular values are positive so the left/right singular vectors differ by a sign when the corresponding eigenvalue is negative.

This means that, when doing the cut, with the SVD negative eigenvalues become more negative, while with diagonalization negative eigenvalues become positive. Intuitively I would prefer the second since the covariance matrix should be positive, however I'm not sure because maybe the first option introduces less bias in the results.

In any case, it would be more efficient to call a diagonalization routine:

```python
from scipy import linalg
import numpy as np
a = np.random.randn(300, 300)
cov = a.T @ a
%timeit linalg.svd(cov)
%timeit linalg.eigh(cov)
```

Output:

```
147 ms ± 4.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
70.5 ms ± 2.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by gplepage** [comment]
The reason it uses ``svd`` rather than ``eigh`` is because ``svd`` proved to be more robust; ``eigh`` was more likely to generate failed-to-converge errors, which were very irritating for users. On the to-do list for some time is to check out the several options in ``scipy`` for doing this. That is more likely to happen now that ``scipy`` is required for ``gvar.``

**Comment by Gattocrucco** [comment]
Ok, so maybe gvar.SVD could use eigh by default and switch to svd in case of convergence error?

**Comment by gplepage** [comment]
Right now eigh is used as a backup for svd -- so the opposite of what you are suggesting. 

The next version (coming soon) will allow you to switch eigh and svd, so eigh is used by default. gvar.SVD will choose its eigen analyzer from a dictionary gvar.SVD._analyzers. The default analyzer is the first one in the dictionary. The two entries initially will be numpy's svd and eigh, in that order. So if one wants to change the default to eigh, one makes a new dictionary with the same contents as gvar.SVD._analyzers but in the opposite order. Then one sets gvar.SVD._analyzers equal to the new dictionary. One could do this (once) right after importing gvar.

I may change the default to eigh but doing so will inconvenience users because it can cause complex fits to give slightly different results (not significantly different but different). So fits they did before upgrading will look slightly different from the same fits after upgrading, which worries people. If I make a change, therefore, I only want to do it once. But before doing so I want to study the various scipy/LAPACK routines for eigen analyses. I already know that some of them are not very accurate for the kinds of very ill-conditioned correlation matrices that occur in fits, but I need to do a more systematic study. The introduction of gvar.SVD._analyzers will make it easier for me to test a variety of options.

**Comment by Gattocrucco** [comment]
Thanks, this interface would be useful.

Since you are taking some time to look into this and to make a general interface, I'll make a further request. The fastest way I know to get correlated samples or decompose a covariance matrix for doing a least squares fit is Cholesky. It is 10 times faster than diagonalization, so it really makes a difference.

Although Cholesky just can not be done if the matrix is not positive definite, up to now I always had success with very ill matrices with the simple method of adding an epsilon to the diagonal.

The epsilon to add is the same you would use for an svd cut, so you have to know the largest eigenvalue. Luckily there's a simple fast O(n^2) method for getting an upper bound on the largest magnitude eigenvalue, the Gershgorin theorem, and luckily the bound tends to be actually a good estimate for the kind of ill-conditioned matrices that appear in statistics (at least the ones that I encountered).

I've never worked with very unbalanced covariance matrices i.e. very different variances; I guess that would be solved by first using something like scipy.linalg.matrix_balance, but I have not tried.

So it would be useful if this could be used by gvar.raniter and lsqfit, but it does not really fit into gvar.SVD as it is now, so don't take this as an urgent request, since anyway the bottleneck is still in evalcov and evalcov_blocks in general.

Code for decomposition benchmark:

```python
from scipy import linalg
import numpy as np
a = np.random.randn(100, 100)
c = a.T @ a
%timeit linalg.cholesky(c)
%timeit linalg.eigh(c)
```

Output:

```
842 µs ± 217 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
9.82 ms ± 955 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Code for Cholesky+Gershgorin:

```python
x = np.linspace(0, 1, 100)
cov = np.exp(-(x[:, None] - x[None, :]) ** 2)
w = linalg.eigvalsh(cov)
print(np.min(w))
print(np.max(w))
gersh_bound = np.max(np.sum(np.abs(cov), axis=-1))
print(gersh_bound)
try:
    linalg.cholesky(cov)
except linalg.LinAlgError:
    print('failed')
U = linalg.cholesky(cov + np.diag(np.full(len(cov), len(cov) * np.finfo(float).eps * gersh_bound)))
print(np.max(np.abs(cov - U.T @ U)))
```

Output:

```
-1.7897229803186643e-14
86.2632276091192
92.10915243244395
failed
2.0456969451743134e-12
```

**Comment by gplepage** [comment]
This is an interesting idea. I knew about cholesky but I didn't know how to regulate it as simply as you do here. It looks quite practical. 

I have to think through the complications. For example, one issue will be selecting the size of the cutoff eps. There are a lot of applications where eps has to be quite large (eg, 1e-2) because the correlation matrix has many small eigenvalues that are badly underestimated. Such large cutoffs affect the precision of your results so you need to select eps carefully. There are techniques using the eigenvalues that allow you to select the SVD eps more or less automatically. I need to think what the analogue would be in this approach.

**Comment by gplepage** [comment]
I will add cholesky to lsqfit. It will take a while to fully test it. In the meantime, you can replace svd by eigh as described above.

**Comment by gplepage** [comment]
Forgot to close out this discussion. gvar now uses scipy's eigh rather than svd. Also cholesky decomposition is now available for use in both gvar and lsqfit. Thanks.

**Comment by gplepage** [comment]
I am closing this issue because the features requested are now available in the software.
