### ISSUE TITLE
Moving dataset.pyx to dataset.py for better autocompletion in editors or IDEs.

### ISSUE THREAD

**Issue by SaltyChiang** [gplepage/gvar#18]
It seems that nothing is defined as a c function or c class in `dataset.pyx`, so I thought we can make it a normal python file.

I renamed `dataset.pyx` to `dataset.py`, commented line 53 and 55, remove `int` type for `binsize` in line 563, chang the latter `is` to `==` in line 621, and commented line 67 in `setup.py`, then `gvar.dataset` seems to work fine.

There might be some extra things I didn't check, and more changes should be applied to the file to make it more pythonic.

**Comment by SaltyChiang** [comment]
I noticed you have some unittest files, and all tests pass after the modification.

**Comment by gplepage** [comment]
It works because ``dataset.pyx`` used to be ``dataset.py``. I converted it into Cython because that sometimes gives a performance boost (even for pure Python code) -- the Cython people say 20-50% improvement. I haven't measured carefully but felt there was little downside to making it a ``.pyx`` code, especially since some of its applications are pretty time consuming. I will at some point tinker more with Cython optimizations.

So I expect there should be no problem converting back to a ``.py`` code, as you indicated, but I probably won't make the change in the standard distribution.

**Comment by SaltyChiang** [comment]
I see.
This file is originally written in python means we can write a stub file for it easily, would you mind adding some *.pyi files for better code autocompletion?
I will close this issue as this is another topic.
