### ISSUE TITLE
Bug: scalar multiplication

### ISSUE THREAD

**Issue by etneil** [gplepage/gvar#38]
I have not been able to track down exactly what caused this issue to start happening, but after installing gvar on a new machine I found that a very simple line of old code was now broken:

```
>>> import gvar as gv
>>> gv.gvar("1(2)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/gvar/_gvarcore.pyx", line 982, in gvar._gvarcore.GVarFactory.__call__
  File "src/gvar/_gvarcore.pyx", line 1017, in gvar._gvarcore.GVarFactory._call1
TypeError: unsupported operand type(s) for *: 'float' and 'gvar._gvarcore.GVar'
>>> 
```

This seems to be a manifestation of a simpler issue, which is that scalar multiplication does not work depending on the order of operations:

```
>>> a = 3.0
>>> b = gv.gvar(1,1)
>>> b*a
3.0(3.0)
>>> a*b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for *: 'float' and 'gvar._gvarcore.GVar'
>>> 
```

I am using Python 3.11.4 and gvar 11.11.11, although I tried creating a Python 3.9 environment and bumped into the same problem so I don't think it's 3.11 specific.  I'm on MacOS Ventura with M2 CPU.

I think this can be fixed (without breaking anything else) by defining an `__rmul__` procedure in _gvarcore.pyx.  Here is a patch that appears to fix the issues noted above for me, although I am not certain whether any edge cases need to be handled:

```
    def __rmul__(xx,yy):
        return xx.__mul__(yy)
```

**Comment by gplepage** [comment]
What version of ``cython`` have you installed?

**Comment by gplepage** [comment]
I ask about ``cython`` because it is undergoing a rather significant change right now (to version 3.0). The bug you are reporting sounds it is caused by version 3.0  which handles __mul__, __add__, etc differently from earlier versions (eg, 0.29). The two are incompatible. If you have been using v3.0 of ``cython``, you can get things going again by replacing it with one of the version 0.29 ``cython``s. 

I will make things work with both versions but it is going to take time.

**Comment by etneil** [comment]
Aha, I hadn't realized there had been a major Cython version change.  I can confirm the bug is indeed due to Cython 3.0, with Cython 0.29 the code examples above work with no changes.  Thanks for the quick reply!

For posterity, I'll note here that setting the Cython directive `c_api_binop_methods=True` is [supposed to restore the old behavior](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#arithmetic-special-methods) and might resolve this issue (although I haven't looked to see if there are other problems lurking in using Cython 3.0 with current gvar.)

**Comment by gplepage** [comment]
You are correct that setting the directive removes most of the problem here. Elsewhere, however, Cython3 is causing some very bizarre problems for me. This may take a while to sort out.

**Comment by etneil** [comment]
A small plot twist: although installing Cython 3.0 was able to trigger the bug, in trying on my desktop this afternoon I have now found that I get the same bug even with Cython 0.29.35 installed if I install any version of gvar >= 11.11.3.  This seems to happen with both Python 3.9 and 3.11.  I was also able to get the same bug with no version of Cython installed, so I presume it has something to do with how Cython is optionally called after 11.11.3?

I am using Anaconda for these tests, with a clean environment, then installing numpy and cython via conda, then pip installing gvar.

For now I have reverted to gvar 11.11.2 and everything seems to be working normally...

**Comment by gplepage** [comment]
Yes, this is the correct behavior. The problem is that the Cython used when installing is not the Cython installed in your Python system. This is a consequence of the way Python builds modules now (which is different from before). Version 11.11.2 and earlier versions use the old method for building modules, and they will use the Cython in your system. 

I just about have everything working properly again, but I am traveling and so won't be able to update the software until the weekend. In the meantime using version 11.11.2 might be the easiest thing to do.

**Comment by etneil** [comment]
Absolutely no rush at all (especially since I have a workaround), I just wanted to share details to hopefully make things easier to diagnose, and to help anyone else who might have bumped into this issue.  Thanks again for being so responsive!

**Comment by gplepage** [comment]
Version 11.11.12 (just posted) should fix this problem. Thanks again for flagging it.

**Comment by etneil** [comment]
Confirmed that upgrading to 11.11.12 using pip fixes the issue on my end, also tried building from source in an environment with Cython 3 and the bug is also fixed.  Thanks!
