### ISSUE TITLE
gvar.cov does not check the gvars are compatible

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#8]
```python
import gvar
x = gvar.gvar_factory()(0, 1)
y = gvar.gvar_factory()(0, 1)
print(gvar.cov(x, y))
```

Result: `1.0`. It should be either 0 or raise an error.

**Comment by Gattocrucco** [comment]
`evalcov` and `evalcov_blocks` have the same problem:

```python
import gvar
x = [gvar.gvar_factory()(0, 1), gvar.gvar_factory()(0, 1)]
print(gvar.evalcov(x))
print(gvar.evalcov_blocks(x))
print(gvar.evalcov_blocks(x, compress=True))
```

Output:

```
[[1. 1.]
 [1. 1.]]
[(array([0, 1]), array([[1., 1.],
       [1., 1.]]))]
[(array([], dtype=int64), array([], dtype=float64)), (array([0, 1]), array([[1., 1.],
       [1., 1.]]))]
```

**Comment by gplepage** [comment]
This, like your other issue, was the result of a conscious decision to leave it up to the user to make sure they weren't violating a rule (that is, don't mix ``GVars`` from different ``gvar_factory`` functions). Almost no one uses more than one ``gvar_factory`` so it hasn't been necessary (or worth the time) to build in lots of protections. The one place where there is protection is in arithmetic and that usually detects such problems, in the few places where they can arise.

In any case there is little point adding protections to ``evalcov`` and ``evalcov_blocks`` since the problem is much more widespread. It is more important to stress that people make it structurally impossible for their codes to mix ``GVars`` from different ``gvar_factory`` functions. Such mixing is unsupported and will give unpredictable results. (I should probably add this last sentence to the documentation.)

**Comment by Gattocrucco** [comment]
I had seen the "non compatible gvars" errors sometimes so I assumed that the standard was to handle it, so yes please add it to the documentation and to the docstrings of gvar_factory and switch_gvar that the behaviour is undefined, I found out this because I assumed that evalcov would treat different gvars as uncorrelated, while arithmetic was forbidden because the results would in general be correlated.
