### ISSUE TITLE
Inconsistent behaviour with asymmetric covariance matrices

### ISSUE THREAD

**Issue by Gattocrucco** [gplepage/gvar#9]
```python
import gvar
x = gvar.gvar([0, 0], [[1, 0.1], [0.9, 1]])
print(gvar.evalcov(x))
print(gvar.evalcov_blocks(x))
print(gvar.cov(x[0], x[1]))
print(gvar.cov(x[1], x[0]))
```

Output:

```
[[1.  0.9]
 [0.9 1. ]]
[(array([0, 1]), array([[1. , 0.9],
       [0.9, 1. ]]))]
0.9
0.1
```

So: `gvar.gvar` stores the full covariance matrix, but `gvar.evalcov` and `gvar.evalcov_blocks` only read the lower triangular part. The original matrix can be recovered with `gvar.cov`.

I think that one or more of the following should be implemented:

  1. Check that the convariance matrix is symmetrical in `gvar.gvar`.

  2. `gvar.gvar` computes the symmetrical part of the matrix.
  
  3. Read only the lower/upper triangular part in `gvar.gvar`, controlled by a parameter `lower: bool` like in `scipy.linalg`. Would also apply to dictionaries.

  4. `gvar.evalcov` and `gvar.evalcov_blocks` read all the matrix.

  5. `gvar.cov` reads only the lower triangular part.

Personally I prefer option (4) because it seems the simplest to implement. Also, since in general `gvar` and `lsqfit` use SVD instead of diagonalization or cholesky, the full matrix is always used, so this would be consistent with the rest of the library.

**Comment by gplepage** [comment]
This is more a feature request, again, not really a bug. There are many things that won't work if ``gvar.gvar`` is given a bad covariance matrix; I won't promise the consistency of anything in cases like your example.

In general, the covariance matrices must be symmetric and positive definite. It is too costly to check this, however, in every call to ``gvar.gvar,`` especially for large matrices. So I decided a long time ago not to check the validity of covariance matrices, for the sake of speed. In practice this has caused few or no problems because covariance matrices are typically computed by other software that guarantees that they are properly assembled. 

``gvar.cov`` is heavily used by this module and the coding of multiple functions is simplified by having the full matrix stored, not just the upper or lower triangular part. It is on the to-do list to change this someday, in order to save memory, but it would involve a lot of coding and might slow down some of the critical routines. Adding a ``lower`` option might make sense then.

The documentation should probably state more clearly that bad covariance matrices are bad, and that it is up to the user to check them. The next version of ``gvar`` will have a new keyword option for ``gvar.gvar:`` setting keyword ``verify=True`` will cause it to check that the covariance matrix is positive definite and symmetric. The default value for ``verify`` will be ``False,`` however, because of the performance hit for large matrices. It will check for symmetry no matter what the value of ``verify.``

**Comment by Gattocrucco** [comment]
Ok, so you already planned to add the symmetry check, this will completely solve the issue.

**Comment by gplepage** [comment]
Actually I wasn't planning to add a symmetry check until you asked for it. That prodded me to put one in. Thanks.
